// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.5.1
// source: proto/micro_mall_trolley_proto/trolley_business/trolley_business.proto

package trolley_business

import (
	context "context"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_SHOP_NOT_EXIST     RetCode = 50005
	RetCode_SHOP_EXIST         RetCode = 50006
	RetCode_SKU_NOT_EXIST      RetCode = 50007
	RetCode_SKU_EXIST          RetCode = 50008
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0:     "SUCCESS",
		500:   "ERROR",
		50001: "USER_NOT_EXIST",
		50002: "USER_EXIST",
		50003: "MERCHANT_NOT_EXIST",
		50004: "MERCHANT_EXIST",
		50005: "SHOP_NOT_EXIST",
		50006: "SHOP_EXIST",
		50007: "SKU_NOT_EXIST",
		50008: "SKU_EXIST",
	}
	RetCode_value = map[string]int32{
		"SUCCESS":            0,
		"ERROR":              500,
		"USER_NOT_EXIST":     50001,
		"USER_EXIST":         50002,
		"MERCHANT_NOT_EXIST": 50003,
		"MERCHANT_EXIST":     50004,
		"SHOP_NOT_EXIST":     50005,
		"SHOP_EXIST":         50006,
		"SKU_NOT_EXIST":      50007,
		"SKU_EXIST":          50008,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{0}
}

type OperationType int32

const (
	OperationType_CREATE   OperationType = 0
	OperationType_UPDATE   OperationType = 1
	OperationType_DELETE   OperationType = 2
	OperationType_AUDIT    OperationType = 3
	OperationType_PUT_AWAY OperationType = 4
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "AUDIT",
		4: "PUT_AWAY",
	}
	OperationType_value = map[string]int32{
		"CREATE":   0,
		"UPDATE":   1,
		"DELETE":   2,
		"AUDIT":    3,
		"PUT_AWAY": 4,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{1}
}

type GetUserTrolleyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserTrolleyListRequest) Reset() {
	*x = GetUserTrolleyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTrolleyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTrolleyListRequest) ProtoMessage() {}

func (x *GetUserTrolleyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTrolleyListRequest.ProtoReflect.Descriptor instead.
func (*GetUserTrolleyListRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserTrolleyListRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserTrolleyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common  *CommonResponse      `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Records []*UserTrolleyRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *GetUserTrolleyListResponse) Reset() {
	*x = GetUserTrolleyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTrolleyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTrolleyListResponse) ProtoMessage() {}

func (x *GetUserTrolleyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTrolleyListResponse.ProtoReflect.Descriptor instead.
func (*GetUserTrolleyListResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserTrolleyListResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetUserTrolleyListResponse) GetRecords() []*UserTrolleyRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type UserTrolleyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuCode  string `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ShopId   int64  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Time     string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Count    int64  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Selected bool   `protobuf:"varint,6,opt,name=selected,proto3" json:"selected,omitempty"`
}

func (x *UserTrolleyRecord) Reset() {
	*x = UserTrolleyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTrolleyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTrolleyRecord) ProtoMessage() {}

func (x *UserTrolleyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTrolleyRecord.ProtoReflect.Descriptor instead.
func (*UserTrolleyRecord) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{2}
}

func (x *UserTrolleyRecord) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *UserTrolleyRecord) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *UserTrolleyRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *UserTrolleyRecord) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UserTrolleyRecord) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type RemoveSkuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SkuCode string `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ShopId  int64  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *RemoveSkuRequest) Reset() {
	*x = RemoveSkuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkuRequest) ProtoMessage() {}

func (x *RemoveSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkuRequest.ProtoReflect.Descriptor instead.
func (*RemoveSkuRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveSkuRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RemoveSkuRequest) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *RemoveSkuRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type RemoveSkuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *RemoveSkuResponse) Reset() {
	*x = RemoveSkuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSkuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkuResponse) ProtoMessage() {}

func (x *RemoveSkuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkuResponse.ProtoReflect.Descriptor instead.
func (*RemoveSkuResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSkuResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

type JoinSkuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SkuCode  string `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ShopId   int64  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Time     string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Count    int64  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Selected bool   `protobuf:"varint,6,opt,name=selected,proto3" json:"selected,omitempty"`
}

func (x *JoinSkuRequest) Reset() {
	*x = JoinSkuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSkuRequest) ProtoMessage() {}

func (x *JoinSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSkuRequest.ProtoReflect.Descriptor instead.
func (*JoinSkuRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{5}
}

func (x *JoinSkuRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *JoinSkuRequest) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *JoinSkuRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *JoinSkuRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *JoinSkuRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *JoinSkuRequest) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type JoinSkuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *JoinSkuResponse) Reset() {
	*x = JoinSkuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSkuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSkuResponse) ProtoMessage() {}

func (x *JoinSkuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSkuResponse.ProtoReflect.Descriptor instead.
func (*JoinSkuResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{6}
}

func (x *JoinSkuResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code RetCode `protobuf:"varint,1,opt,name=code,proto3,enum=trolley_business.RetCode" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP(), []int{7}
}

func (x *CommonResponse) GetCode() RetCode {
	if x != nil {
		return x.Code
	}
	return RetCode_SUCCESS
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto protoreflect.FileDescriptor

var file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDesc = []byte{
	0x0a, 0x46, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x5f, 0x6d, 0x61,
	0x6c, 0x6c, 0x5f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x2f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x1a, 0x3e, 0x67, 0x69, 0x74, 0x65,
	0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x6c, 0x76, 0x69, 0x6e, 0x73, 0x2d, 0x69, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x22, 0x58, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x11, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x4a,
	0x6f, 0x69, 0x6e, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x4b, 0x0a, 0x0f, 0x4a, 0x6f, 0x69,
	0x6e, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79,
	0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0xc8, 0x01, 0x0a, 0x07, 0x52, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xf4, 0x03, 0x12, 0x14,
	0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54,
	0x10, 0xd1, 0x86, 0x03, 0x12, 0x10, 0x0a, 0x0a, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x45, 0x58, 0x49,
	0x53, 0x54, 0x10, 0xd2, 0x86, 0x03, 0x12, 0x18, 0x0a, 0x12, 0x4d, 0x45, 0x52, 0x43, 0x48, 0x41,
	0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd3, 0x86, 0x03,
	0x12, 0x14, 0x0a, 0x0e, 0x4d, 0x45, 0x52, 0x43, 0x48, 0x41, 0x4e, 0x54, 0x5f, 0x45, 0x58, 0x49,
	0x53, 0x54, 0x10, 0xd4, 0x86, 0x03, 0x12, 0x14, 0x0a, 0x0e, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd5, 0x86, 0x03, 0x12, 0x10, 0x0a, 0x0a,
	0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd6, 0x86, 0x03, 0x12, 0x13,
	0x0a, 0x0d, 0x53, 0x4b, 0x55, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10,
	0xd7, 0x86, 0x03, 0x12, 0x0f, 0x0a, 0x09, 0x53, 0x4b, 0x55, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54,
	0x10, 0xd8, 0x86, 0x03, 0x2a, 0x4c, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44,
	0x49, 0x54, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x55, 0x54, 0x5f, 0x41, 0x57, 0x41, 0x59,
	0x10, 0x04, 0x32, 0x8f, 0x03, 0x0a, 0x16, 0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a,
	0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x6b, 0x75, 0x12, 0x20, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x19, 0x1a, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x79, 0x2f, 0x73, 0x6b, 0x75, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x74,
	0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x75, 0x12, 0x22, 0x2e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x2a, 0x16, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x2f, 0x73, 0x6b, 0x75, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x8d, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x79, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x2f, 0x73, 0x6b, 0x75, 0x2f,
	0x6c, 0x69, 0x73, 0x74, 0x42, 0x42, 0x5a, 0x40, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x5f, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x3b, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x79, 0x5f,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescOnce sync.Once
	file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescData = file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDesc
)

func file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescGZIP() []byte {
	file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescOnce.Do(func() {
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescData)
	})
	return file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDescData
}

var file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_goTypes = []interface{}{
	(RetCode)(0),                       // 0: trolley_business.RetCode
	(OperationType)(0),                 // 1: trolley_business.OperationType
	(*GetUserTrolleyListRequest)(nil),  // 2: trolley_business.GetUserTrolleyListRequest
	(*GetUserTrolleyListResponse)(nil), // 3: trolley_business.GetUserTrolleyListResponse
	(*UserTrolleyRecord)(nil),          // 4: trolley_business.UserTrolleyRecord
	(*RemoveSkuRequest)(nil),           // 5: trolley_business.RemoveSkuRequest
	(*RemoveSkuResponse)(nil),          // 6: trolley_business.RemoveSkuResponse
	(*JoinSkuRequest)(nil),             // 7: trolley_business.JoinSkuRequest
	(*JoinSkuResponse)(nil),            // 8: trolley_business.JoinSkuResponse
	(*CommonResponse)(nil),             // 9: trolley_business.CommonResponse
}
var file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_depIdxs = []int32{
	9, // 0: trolley_business.GetUserTrolleyListResponse.common:type_name -> trolley_business.CommonResponse
	4, // 1: trolley_business.GetUserTrolleyListResponse.records:type_name -> trolley_business.UserTrolleyRecord
	9, // 2: trolley_business.RemoveSkuResponse.common:type_name -> trolley_business.CommonResponse
	9, // 3: trolley_business.JoinSkuResponse.common:type_name -> trolley_business.CommonResponse
	0, // 4: trolley_business.CommonResponse.code:type_name -> trolley_business.RetCode
	7, // 5: trolley_business.TrolleyBusinessService.JoinSku:input_type -> trolley_business.JoinSkuRequest
	5, // 6: trolley_business.TrolleyBusinessService.RemoveSku:input_type -> trolley_business.RemoveSkuRequest
	2, // 7: trolley_business.TrolleyBusinessService.GetUserTrolleyList:input_type -> trolley_business.GetUserTrolleyListRequest
	8, // 8: trolley_business.TrolleyBusinessService.JoinSku:output_type -> trolley_business.JoinSkuResponse
	6, // 9: trolley_business.TrolleyBusinessService.RemoveSku:output_type -> trolley_business.RemoveSkuResponse
	3, // 10: trolley_business.TrolleyBusinessService.GetUserTrolleyList:output_type -> trolley_business.GetUserTrolleyListResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_init() }
func file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_init() {
	if File_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTrolleyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTrolleyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTrolleyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSkuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSkuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSkuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSkuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_goTypes,
		DependencyIndexes: file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_depIdxs,
		EnumInfos:         file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_enumTypes,
		MessageInfos:      file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_msgTypes,
	}.Build()
	File_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto = out.File
	file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_rawDesc = nil
	file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_goTypes = nil
	file_proto_micro_mall_trolley_proto_trolley_business_trolley_business_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TrolleyBusinessServiceClient is the client API for TrolleyBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrolleyBusinessServiceClient interface {
	// 添加商品到购物车
	JoinSku(ctx context.Context, in *JoinSkuRequest, opts ...grpc.CallOption) (*JoinSkuResponse, error)
	// 从购物车移除商品
	RemoveSku(ctx context.Context, in *RemoveSkuRequest, opts ...grpc.CallOption) (*RemoveSkuResponse, error)
	// 获取用户购物车中的商品
	GetUserTrolleyList(ctx context.Context, in *GetUserTrolleyListRequest, opts ...grpc.CallOption) (*GetUserTrolleyListResponse, error)
}

type trolleyBusinessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrolleyBusinessServiceClient(cc grpc.ClientConnInterface) TrolleyBusinessServiceClient {
	return &trolleyBusinessServiceClient{cc}
}

func (c *trolleyBusinessServiceClient) JoinSku(ctx context.Context, in *JoinSkuRequest, opts ...grpc.CallOption) (*JoinSkuResponse, error) {
	out := new(JoinSkuResponse)
	err := c.cc.Invoke(ctx, "/trolley_business.TrolleyBusinessService/JoinSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trolleyBusinessServiceClient) RemoveSku(ctx context.Context, in *RemoveSkuRequest, opts ...grpc.CallOption) (*RemoveSkuResponse, error) {
	out := new(RemoveSkuResponse)
	err := c.cc.Invoke(ctx, "/trolley_business.TrolleyBusinessService/RemoveSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trolleyBusinessServiceClient) GetUserTrolleyList(ctx context.Context, in *GetUserTrolleyListRequest, opts ...grpc.CallOption) (*GetUserTrolleyListResponse, error) {
	out := new(GetUserTrolleyListResponse)
	err := c.cc.Invoke(ctx, "/trolley_business.TrolleyBusinessService/GetUserTrolleyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrolleyBusinessServiceServer is the server API for TrolleyBusinessService service.
type TrolleyBusinessServiceServer interface {
	// 添加商品到购物车
	JoinSku(context.Context, *JoinSkuRequest) (*JoinSkuResponse, error)
	// 从购物车移除商品
	RemoveSku(context.Context, *RemoveSkuRequest) (*RemoveSkuResponse, error)
	// 获取用户购物车中的商品
	GetUserTrolleyList(context.Context, *GetUserTrolleyListRequest) (*GetUserTrolleyListResponse, error)
}

// UnimplementedTrolleyBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrolleyBusinessServiceServer struct {
}

func (*UnimplementedTrolleyBusinessServiceServer) JoinSku(context.Context, *JoinSkuRequest) (*JoinSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinSku not implemented")
}
func (*UnimplementedTrolleyBusinessServiceServer) RemoveSku(context.Context, *RemoveSkuRequest) (*RemoveSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSku not implemented")
}
func (*UnimplementedTrolleyBusinessServiceServer) GetUserTrolleyList(context.Context, *GetUserTrolleyListRequest) (*GetUserTrolleyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTrolleyList not implemented")
}

func RegisterTrolleyBusinessServiceServer(s *grpc.Server, srv TrolleyBusinessServiceServer) {
	s.RegisterService(&_TrolleyBusinessService_serviceDesc, srv)
}

func _TrolleyBusinessService_JoinSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrolleyBusinessServiceServer).JoinSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trolley_business.TrolleyBusinessService/JoinSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrolleyBusinessServiceServer).JoinSku(ctx, req.(*JoinSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrolleyBusinessService_RemoveSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrolleyBusinessServiceServer).RemoveSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trolley_business.TrolleyBusinessService/RemoveSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrolleyBusinessServiceServer).RemoveSku(ctx, req.(*RemoveSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrolleyBusinessService_GetUserTrolleyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTrolleyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrolleyBusinessServiceServer).GetUserTrolleyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trolley_business.TrolleyBusinessService/GetUserTrolleyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrolleyBusinessServiceServer).GetUserTrolleyList(ctx, req.(*GetUserTrolleyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrolleyBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trolley_business.TrolleyBusinessService",
	HandlerType: (*TrolleyBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinSku",
			Handler:    _TrolleyBusinessService_JoinSku_Handler,
		},
		{
			MethodName: "RemoveSku",
			Handler:    _TrolleyBusinessService_RemoveSku_Handler,
		},
		{
			MethodName: "GetUserTrolleyList",
			Handler:    _TrolleyBusinessService_GetUserTrolleyList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_trolley_proto/trolley_business/trolley_business.proto",
}
