// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_order_proto/order_business/order_business.proto

package order_business

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS               RetCode = 0
	RetCode_ERROR                 RetCode = 500
	RetCode_USER_NOT_EXIST        RetCode = 50001
	RetCode_USER_EXIST            RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST    RetCode = 50003
	RetCode_MERCHANT_EXIST        RetCode = 50004
	RetCode_SHOP_NOT_EXIST        RetCode = 50005
	RetCode_SHOP_EXIST            RetCode = 50006
	RetCode_SKU_NOT_EXIST         RetCode = 50007
	RetCode_SKU_EXIST             RetCode = 50008
	RetCode_SKU_AMOUNT_NOT_ENOUGH RetCode = 50009
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
	50005: "SHOP_NOT_EXIST",
	50006: "SHOP_EXIST",
	50007: "SKU_NOT_EXIST",
	50008: "SKU_EXIST",
	50009: "SKU_AMOUNT_NOT_ENOUGH",
}

var RetCode_value = map[string]int32{
	"SUCCESS":               0,
	"ERROR":                 500,
	"USER_NOT_EXIST":        50001,
	"USER_EXIST":            50002,
	"MERCHANT_NOT_EXIST":    50003,
	"MERCHANT_EXIST":        50004,
	"SHOP_NOT_EXIST":        50005,
	"SHOP_EXIST":            50006,
	"SKU_NOT_EXIST":         50007,
	"SKU_EXIST":             50008,
	"SKU_AMOUNT_NOT_ENOUGH": 50009,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE   OperationType = 0
	OperationType_UPDATE   OperationType = 1
	OperationType_DELETE   OperationType = 2
	OperationType_AUDIT    OperationType = 3
	OperationType_PUT_AWAY OperationType = 4
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
	4: "PUT_AWAY",
}

var OperationType_value = map[string]int32{
	"CREATE":   0,
	"UPDATE":   1,
	"DELETE":   2,
	"AUDIT":    3,
	"PUT_AWAY": 4,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{1}
}

type CoinType int32

const (
	CoinType_CNY CoinType = 0
	CoinType_USD CoinType = 1
)

var CoinType_name = map[int32]string{
	0: "CNY",
	1: "USD",
}

var CoinType_value = map[string]int32{
	"CNY": 0,
	"USD": 1,
}

func (x CoinType) String() string {
	return proto.EnumName(CoinType_name, int32(x))
}

func (CoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{2}
}

type AccountState int32

const (
	AccountState_NORMAL  AccountState = 0
	AccountState_LOCK    AccountState = 1
	AccountState_INVALID AccountState = 2
)

var AccountState_name = map[int32]string{
	0: "NORMAL",
	1: "LOCK",
	2: "INVALID",
}

var AccountState_value = map[string]int32{
	"NORMAL":  0,
	"LOCK":    1,
	"INVALID": 2,
}

func (x AccountState) String() string {
	return proto.EnumName(AccountState_name, int32(x))
}

func (AccountState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{3}
}

type AccountType int32

const (
	AccountType_PERSONAL AccountType = 0
	AccountType_COMPANY  AccountType = 1
	AccountType_SYSTEM   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "PERSONAL",
	1: "COMPANY",
	2: "SYSTEM",
}

var AccountType_value = map[string]int32{
	"PERSONAL": 0,
	"COMPANY":  1,
	"SYSTEM":   2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{4}
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=order_business.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{0}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type OrderDetail struct {
	ShopDetail           []*OrderShopDetail `protobuf:"bytes,1,rep,name=shop_detail,json=shopDetail,proto3" json:"shop_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{1}
}

func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (m *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(m, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetShopDetail() []*OrderShopDetail {
	if m != nil {
		return m.ShopDetail
	}
	return nil
}

// 同一个门店的商品
type OrderShopDetail struct {
	ShopId               int64           `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CoinType             CoinType        `protobuf:"varint,6,opt,name=coin_type,json=coinType,proto3,enum=order_business.CoinType" json:"coin_type,omitempty"`
	Goods                []*OrderGoods   `protobuf:"bytes,7,rep,name=goods,proto3" json:"goods,omitempty"`
	SceneInfo            *OrderSceneInfo `protobuf:"bytes,199,opt,name=scene_info,json=sceneInfo,proto3" json:"scene_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrderShopDetail) Reset()         { *m = OrderShopDetail{} }
func (m *OrderShopDetail) String() string { return proto.CompactTextString(m) }
func (*OrderShopDetail) ProtoMessage()    {}
func (*OrderShopDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{2}
}

func (m *OrderShopDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderShopDetail.Unmarshal(m, b)
}
func (m *OrderShopDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderShopDetail.Marshal(b, m, deterministic)
}
func (m *OrderShopDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderShopDetail.Merge(m, src)
}
func (m *OrderShopDetail) XXX_Size() int {
	return xxx_messageInfo_OrderShopDetail.Size(m)
}
func (m *OrderShopDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderShopDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderShopDetail proto.InternalMessageInfo

func (m *OrderShopDetail) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *OrderShopDetail) GetCoinType() CoinType {
	if m != nil {
		return m.CoinType
	}
	return CoinType_CNY
}

func (m *OrderShopDetail) GetGoods() []*OrderGoods {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *OrderShopDetail) GetSceneInfo() *OrderSceneInfo {
	if m != nil {
		return m.SceneInfo
	}
	return nil
}

type OrderGoods struct {
	SkuCode              string   `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderGoods) Reset()         { *m = OrderGoods{} }
func (m *OrderGoods) String() string { return proto.CompactTextString(m) }
func (*OrderGoods) ProtoMessage()    {}
func (*OrderGoods) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{3}
}

func (m *OrderGoods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderGoods.Unmarshal(m, b)
}
func (m *OrderGoods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderGoods.Marshal(b, m, deterministic)
}
func (m *OrderGoods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderGoods.Merge(m, src)
}
func (m *OrderGoods) XXX_Size() int {
	return xxx_messageInfo_OrderGoods.Size(m)
}
func (m *OrderGoods) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderGoods.DiscardUnknown(m)
}

var xxx_messageInfo_OrderGoods proto.InternalMessageInfo

func (m *OrderGoods) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *OrderGoods) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderGoods) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderGoods) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 一个店铺的商品算一个订单，如果同时包含多个店铺则有多个订单
type CreateOrderRequest struct {
	Uid                  int64        `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Time                 string       `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PayerClientIp        string       `protobuf:"bytes,4,opt,name=payer_client_ip,json=payerClientIp,proto3" json:"payer_client_ip,omitempty"`
	DeviceId             string       `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Detail               *OrderDetail `protobuf:"bytes,299,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{4}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateOrderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CreateOrderRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateOrderRequest) GetPayerClientIp() string {
	if m != nil {
		return m.PayerClientIp
	}
	return ""
}

func (m *CreateOrderRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *CreateOrderRequest) GetDetail() *OrderDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

// 支付场景信息
type OrderSceneInfo struct {
	StoreInfo            *StoreInfo `protobuf:"bytes,999,opt,name=store_info,json=storeInfo,proto3" json:"store_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderSceneInfo) Reset()         { *m = OrderSceneInfo{} }
func (m *OrderSceneInfo) String() string { return proto.CompactTextString(m) }
func (*OrderSceneInfo) ProtoMessage()    {}
func (*OrderSceneInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{5}
}

func (m *OrderSceneInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSceneInfo.Unmarshal(m, b)
}
func (m *OrderSceneInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSceneInfo.Marshal(b, m, deterministic)
}
func (m *OrderSceneInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSceneInfo.Merge(m, src)
}
func (m *OrderSceneInfo) XXX_Size() int {
	return xxx_messageInfo_OrderSceneInfo.Size(m)
}
func (m *OrderSceneInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSceneInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSceneInfo proto.InternalMessageInfo

func (m *OrderSceneInfo) GetStoreInfo() *StoreInfo {
	if m != nil {
		return m.StoreInfo
	}
	return nil
}

// 门店信息
type StoreInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AreaCode             string   `protobuf:"bytes,3,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreInfo) Reset()         { *m = StoreInfo{} }
func (m *StoreInfo) String() string { return proto.CompactTextString(m) }
func (*StoreInfo) ProtoMessage()    {}
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{6}
}

func (m *StoreInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreInfo.Unmarshal(m, b)
}
func (m *StoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreInfo.Marshal(b, m, deterministic)
}
func (m *StoreInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreInfo.Merge(m, src)
}
func (m *StoreInfo) XXX_Size() int {
	return xxx_messageInfo_StoreInfo.Size(m)
}
func (m *StoreInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StoreInfo proto.InternalMessageInfo

func (m *StoreInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StoreInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoreInfo) GetAreaCode() string {
	if m != nil {
		return m.AreaCode
	}
	return ""
}

func (m *StoreInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type OrderEntry struct {
	OrderCode            string   `protobuf:"bytes,10,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	TimeExpire           string   `protobuf:"bytes,11,opt,name=time_expire,json=timeExpire,proto3" json:"time_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderEntry) Reset()         { *m = OrderEntry{} }
func (m *OrderEntry) String() string { return proto.CompactTextString(m) }
func (*OrderEntry) ProtoMessage()    {}
func (*OrderEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{7}
}

func (m *OrderEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderEntry.Unmarshal(m, b)
}
func (m *OrderEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderEntry.Marshal(b, m, deterministic)
}
func (m *OrderEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderEntry.Merge(m, src)
}
func (m *OrderEntry) XXX_Size() int {
	return xxx_messageInfo_OrderEntry.Size(m)
}
func (m *OrderEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OrderEntry proto.InternalMessageInfo

func (m *OrderEntry) GetOrderCode() string {
	if m != nil {
		return m.OrderCode
	}
	return ""
}

func (m *OrderEntry) GetTimeExpire() string {
	if m != nil {
		return m.TimeExpire
	}
	return ""
}

type CreateOrderResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	OrderList            []*OrderEntry   `protobuf:"bytes,2,rep,name=order_list,json=orderList,proto3" json:"order_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{8}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *CreateOrderResponse) GetOrderList() []*OrderEntry {
	if m != nil {
		return m.OrderList
	}
	return nil
}

func init() {
	proto.RegisterEnum("order_business.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("order_business.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("order_business.CoinType", CoinType_name, CoinType_value)
	proto.RegisterEnum("order_business.AccountState", AccountState_name, AccountState_value)
	proto.RegisterEnum("order_business.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*CommonResponse)(nil), "order_business.CommonResponse")
	proto.RegisterType((*OrderDetail)(nil), "order_business.OrderDetail")
	proto.RegisterType((*OrderShopDetail)(nil), "order_business.OrderShopDetail")
	proto.RegisterType((*OrderGoods)(nil), "order_business.OrderGoods")
	proto.RegisterType((*CreateOrderRequest)(nil), "order_business.CreateOrderRequest")
	proto.RegisterType((*OrderSceneInfo)(nil), "order_business.OrderSceneInfo")
	proto.RegisterType((*StoreInfo)(nil), "order_business.StoreInfo")
	proto.RegisterType((*OrderEntry)(nil), "order_business.OrderEntry")
	proto.RegisterType((*CreateOrderResponse)(nil), "order_business.CreateOrderResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_order_proto/order_business/order_business.proto", fileDescriptor_0ca098091950ff88)
}

var fileDescriptor_0ca098091950ff88 = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0xae, 0xe3, 0x36, 0x7f, 0x8e, 0xb7, 0xa9, 0x35, 0xdb, 0xfd, 0xad, 0xb7, 0xfd, 0xc1, 0x56,
	0x46, 0x42, 0x55, 0x10, 0x0d, 0x5b, 0x16, 0x24, 0xb8, 0x58, 0x6d, 0x70, 0xac, 0x6d, 0xd4, 0x34,
	0xae, 0xec, 0x04, 0xe8, 0x95, 0xe5, 0xb5, 0xa7, 0xdd, 0x51, 0x13, 0x8f, 0xf1, 0x38, 0x15, 0xbd,
	0xe5, 0x22, 0x42, 0xe2, 0x92, 0xc7, 0xe0, 0x41, 0xb8, 0x86, 0x02, 0x0b, 0xf7, 0x20, 0x5e, 0x80,
	0x07, 0x40, 0x73, 0xc6, 0xe9, 0xa6, 0xd9, 0xb2, 0x77, 0x67, 0x3e, 0x7f, 0x73, 0xe6, 0x9b, 0xef,
	0x9c, 0x39, 0x86, 0xa7, 0x59, 0xce, 0x0b, 0xde, 0x9e, 0xb0, 0x38, 0xe7, 0xe1, 0x24, 0x1a, 0x8f,
	0x43, 0x9e, 0x27, 0x34, 0x0f, 0x15, 0xac, 0xe2, 0xe7, 0x53, 0xc1, 0x52, 0x2a, 0xc4, 0xd2, 0x72,
	0x0f, 0x39, 0xa4, 0x79, 0x13, 0xdd, 0x7a, 0x72, 0xc6, 0x0a, 0x4a, 0xf7, 0x62, 0x3e, 0x69, 0x9f,
	0xd3, 0xf1, 0x05, 0x4b, 0xc5, 0xfb, 0x8c, 0xb7, 0x63, 0x3e, 0x99, 0xf0, 0xb4, 0xad, 0xd2, 0x9e,
	0x71, 0x7e, 0x36, 0xa6, 0xed, 0x28, 0x63, 0xed, 0x28, 0x4d, 0x79, 0x11, 0x15, 0x8c, 0xa7, 0x65,
	0x3e, 0xdb, 0x83, 0xa6, 0x83, 0x64, 0x9f, 0x8a, 0x8c, 0xa7, 0x82, 0x92, 0xf7, 0x60, 0x35, 0xe6,
	0x09, 0xb5, 0xb4, 0x1d, 0x6d, 0xb7, 0xb9, 0x7f, 0x7f, 0x6f, 0x49, 0x86, 0x4f, 0x0b, 0x87, 0x27,
	0xd4, 0x47, 0x12, 0x31, 0x41, 0x9f, 0x88, 0x33, 0xab, 0xb2, 0xa3, 0xed, 0x36, 0x7c, 0x19, 0xda,
	0x1e, 0x18, 0x9e, 0xdc, 0xd1, 0xa5, 0x45, 0xc4, 0xc6, 0xe4, 0x29, 0x18, 0xe2, 0x05, 0xcf, 0xc2,
	0x04, 0x97, 0x96, 0xb6, 0xa3, 0xef, 0x1a, 0xfb, 0x0f, 0x97, 0x93, 0xe2, 0x8e, 0xe0, 0x05, 0xcf,
	0xd4, 0x2e, 0x1f, 0xc4, 0x75, 0x6c, 0x5f, 0x69, 0xb0, 0xb1, 0xf4, 0x9d, 0xdc, 0x87, 0x1a, 0x66,
	0x65, 0x09, 0xca, 0xd4, 0xfd, 0xaa, 0x5c, 0xf6, 0x12, 0xf2, 0x11, 0x34, 0x62, 0xce, 0xd2, 0xb0,
	0xb8, 0xcc, 0xa8, 0x55, 0xc5, 0x1b, 0x58, 0xcb, 0x87, 0x39, 0x9c, 0xa5, 0xc3, 0xcb, 0x8c, 0xfa,
	0xf5, 0xb8, 0x8c, 0xc8, 0x07, 0xb0, 0x76, 0xc6, 0x79, 0x22, 0xac, 0x1a, 0xea, 0xdb, 0xba, 0x55,
	0xdf, 0x33, 0xc9, 0xf0, 0x15, 0x91, 0x3c, 0x01, 0x10, 0x31, 0x4d, 0x69, 0xc8, 0xd2, 0x53, 0x6e,
	0xfd, 0x28, 0x55, 0x18, 0xfb, 0x6f, 0xdf, 0x7e, 0x2f, 0xc9, 0xeb, 0xa5, 0xa7, 0xdc, 0x6f, 0x88,
	0x79, 0x68, 0x33, 0x80, 0x57, 0x49, 0xc9, 0x03, 0xa8, 0x8b, 0xf3, 0x69, 0x88, 0xbe, 0x2b, 0x2f,
	0x6b, 0xe2, 0x7c, 0x2a, 0x7d, 0x26, 0x9b, 0xb0, 0x96, 0xe5, 0x2c, 0xa6, 0x96, 0x8e, 0xb8, 0x5a,
	0x90, 0xff, 0x41, 0x35, 0x9a, 0xf0, 0x69, 0x5a, 0x58, 0xab, 0xea, 0xfe, 0x6a, 0x45, 0x08, 0xac,
	0xa6, 0xd1, 0x84, 0x5a, 0x6b, 0x48, 0xc6, 0xd8, 0x7e, 0xa9, 0x01, 0x71, 0x72, 0x1a, 0x15, 0x14,
	0x4f, 0xf4, 0xe9, 0x57, 0x53, 0x2a, 0x0a, 0x59, 0xba, 0xe9, 0xb5, 0x7f, 0x32, 0x94, 0x9b, 0x0b,
	0x36, 0x99, 0x2b, 0xc0, 0x98, 0xec, 0x80, 0x91, 0x50, 0x11, 0xe7, 0x2c, 0x93, 0x5d, 0x53, 0x8a,
	0x58, 0x84, 0xc8, 0xbb, 0xb0, 0x91, 0x45, 0x97, 0x34, 0x0f, 0xe3, 0x31, 0xa3, 0x69, 0x11, 0xb2,
	0x0c, 0x35, 0x35, 0xfc, 0x75, 0x84, 0x1d, 0x44, 0x7b, 0x19, 0xd9, 0x86, 0x46, 0x42, 0x2f, 0x58,
	0x4c, 0x65, 0xd5, 0x94, 0xbe, 0xba, 0x02, 0x7a, 0x09, 0x79, 0x0c, 0xd5, 0xb2, 0x43, 0x7e, 0xa8,
	0xa0, 0x95, 0xdb, 0xb7, 0x5a, 0x59, 0xb6, 0x47, 0xc9, 0xb5, 0x0f, 0xa1, 0x79, 0xd3, 0x61, 0xf2,
	0x09, 0x80, 0x28, 0x78, 0x5e, 0x96, 0xe5, 0xef, 0x1a, 0xe6, 0x7a, 0xb0, 0x9c, 0x2b, 0x90, 0x94,
	0xb2, 0x22, 0xf3, 0xd0, 0x3e, 0x85, 0xc6, 0x35, 0x4e, 0x9a, 0x50, 0xb9, 0xf6, 0xa6, 0xa2, 0xac,
	0x41, 0x5f, 0x2b, 0xaf, 0x7c, 0x95, 0x17, 0x8a, 0x72, 0x1a, 0xa9, 0xaa, 0x29, 0x63, 0xea, 0x12,
	0xc0, 0xb2, 0x59, 0x50, 0x8b, 0x92, 0x24, 0xa7, 0x42, 0x94, 0x6e, 0xcc, 0x97, 0x76, 0xbf, 0xac,
	0xbc, 0x9b, 0x16, 0xf9, 0x25, 0x79, 0x0b, 0x40, 0x89, 0xc3, 0x2c, 0x80, 0xd4, 0x06, 0x22, 0x98,
	0xe6, 0x21, 0x18, 0xb2, 0x0c, 0x21, 0xfd, 0x3a, 0x63, 0x39, 0xb5, 0x0c, 0xfc, 0x0e, 0x12, 0x72,
	0x11, 0xb1, 0xbf, 0xd5, 0xe0, 0xee, 0x8d, 0xe2, 0x96, 0xaf, 0xf8, 0x63, 0xa8, 0xaa, 0x21, 0x60,
	0xfd, 0x47, 0x6b, 0xde, 0x7c, 0xf5, 0x7e, 0xc9, 0x96, 0x06, 0x2a, 0xe2, 0x98, 0x89, 0xc2, 0xaa,
	0xbc, 0xe1, 0x39, 0xa0, 0xfe, 0x52, 0x6b, 0x9f, 0x89, 0xa2, 0xf5, 0x97, 0x06, 0xb5, 0x72, 0x3a,
	0x10, 0x03, 0x6a, 0xc1, 0xc8, 0x71, 0xdc, 0x20, 0x30, 0x57, 0x08, 0xc0, 0x9a, 0xeb, 0xfb, 0x9e,
	0x6f, 0xfe, 0xa3, 0x93, 0x4d, 0x68, 0x8e, 0x02, 0xd7, 0x0f, 0x07, 0xde, 0x30, 0x74, 0xbf, 0xec,
	0x05, 0x43, 0xf3, 0xa7, 0x99, 0x4e, 0x4c, 0x00, 0x44, 0x15, 0xf2, 0xf3, 0x4c, 0x27, 0x16, 0x90,
	0x23, 0xd7, 0x77, 0x0e, 0x3a, 0x83, 0xe1, 0x02, 0xf7, 0x6a, 0x86, 0x19, 0xae, 0xbf, 0x28, 0xf4,
	0x17, 0x85, 0x06, 0x07, 0xde, 0xf1, 0x02, 0xf7, 0x57, 0x95, 0x17, 0x51, 0x85, 0xfc, 0x36, 0xd3,
	0xc9, 0x5d, 0x58, 0x0f, 0x0e, 0x47, 0x0b, 0xb4, 0x97, 0x33, 0x9d, 0x6c, 0x40, 0x43, 0x82, 0x0a,
	0xf8, 0x7d, 0xa6, 0x93, 0x6d, 0xb8, 0x27, 0x81, 0xce, 0x91, 0x37, 0x9a, 0x9f, 0x3f, 0xf0, 0x46,
	0xcf, 0x0e, 0xcc, 0x3f, 0x66, 0x7a, 0xab, 0x0f, 0xeb, 0x5e, 0x46, 0x73, 0x1c, 0xa3, 0x38, 0x3d,
	0x00, 0xaa, 0x8e, 0xef, 0x76, 0x86, 0x2e, 0xde, 0xb5, 0x3a, 0x3a, 0xee, 0xca, 0x58, 0x93, 0x71,
	0xd7, 0xed, 0xbb, 0x43, 0xd7, 0xac, 0x90, 0x06, 0xac, 0x75, 0x46, 0xdd, 0xde, 0xd0, 0xd4, 0xc9,
	0x1d, 0xa8, 0x1f, 0x8f, 0x86, 0x61, 0xe7, 0x8b, 0xce, 0x89, 0xb9, 0xda, 0xfa, 0x3f, 0xd4, 0xe7,
	0x03, 0x89, 0xd4, 0x40, 0x77, 0x06, 0x27, 0xe6, 0x8a, 0x0c, 0x46, 0x41, 0xd7, 0xd4, 0x5a, 0x8f,
	0xe0, 0x4e, 0x27, 0x8e, 0xe5, 0xd3, 0x0e, 0x8a, 0xa8, 0xc0, 0xa3, 0x06, 0x9e, 0x7f, 0xd4, 0xe9,
	0x9b, 0x2b, 0xa4, 0x0e, 0xab, 0x7d, 0xcf, 0x39, 0x34, 0x35, 0xe9, 0x76, 0x6f, 0xf0, 0x79, 0xa7,
	0xdf, 0xeb, 0x9a, 0x95, 0xd6, 0x63, 0x30, 0xca, 0x2d, 0x98, 0x53, 0x9e, 0xe6, 0xfa, 0x81, 0x37,
	0xc0, 0x3d, 0x06, 0xd4, 0x1c, 0xef, 0xe8, 0xb8, 0x33, 0x38, 0x51, 0xfa, 0x82, 0x93, 0x60, 0xe8,
	0x1e, 0x99, 0x95, 0xfd, 0xef, 0x34, 0xd8, 0xc4, 0xb2, 0x7e, 0x56, 0x16, 0x39, 0xa0, 0xb9, 0x7c,
	0x9b, 0x44, 0x80, 0xb1, 0xd0, 0x5f, 0xc4, 0x7e, 0xad, 0x8f, 0x5e, 0x9b, 0x2c, 0x5b, 0xef, 0xbc,
	0x91, 0xa3, 0x1a, 0xce, 0xde, 0xfe, 0xe6, 0xea, 0xcf, 0xef, 0x2b, 0xf7, 0x6c, 0xb3, 0x7d, 0xf1,
	0x48, 0xfd, 0xea, 0xda, 0x31, 0xd2, 0x3e, 0xd5, 0x5a, 0xcf, 0xab, 0xf8, 0x73, 0xfa, 0xf0, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x76, 0x83, 0x7b, 0x30, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderBusinessServiceClient is the client API for OrderBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderBusinessServiceClient interface {
	// 创建订单
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderBusinessServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderBusinessServiceClient(cc *grpc.ClientConn) OrderBusinessServiceClient {
	return &orderBusinessServiceClient{cc}
}

func (c *orderBusinessServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order_business.OrderBusinessService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderBusinessServiceServer is the server API for OrderBusinessService service.
type OrderBusinessServiceServer interface {
	// 创建订单
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

// UnimplementedOrderBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderBusinessServiceServer struct {
}

func (*UnimplementedOrderBusinessServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderBusinessServiceServer(s *grpc.Server, srv OrderBusinessServiceServer) {
	s.RegisterService(&_OrderBusinessService_serviceDesc, srv)
}

func _OrderBusinessService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBusinessServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order_business.OrderBusinessService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBusinessServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order_business.OrderBusinessService",
	HandlerType: (*OrderBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderBusinessService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_order_proto/order_business/order_business.proto",
}
