// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: proto/micro_mall_order/proto/micro_mall_users_proto/users/users.proto

package users

import (
	context "context"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_ACCOUNT_EXIST      RetCode = 50005
	RetCode_ACCOUNT_NOT_EXIST  RetCode = 50006
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0:     "SUCCESS",
		500:   "ERROR",
		50001: "USER_NOT_EXIST",
		50002: "USER_EXIST",
		50003: "MERCHANT_NOT_EXIST",
		50004: "MERCHANT_EXIST",
		50005: "ACCOUNT_EXIST",
		50006: "ACCOUNT_NOT_EXIST",
	}
	RetCode_value = map[string]int32{
		"SUCCESS":            0,
		"ERROR":              500,
		"USER_NOT_EXIST":     50001,
		"USER_EXIST":         50002,
		"MERCHANT_NOT_EXIST": 50003,
		"MERCHANT_EXIST":     50004,
		"ACCOUNT_EXIST":      50005,
		"ACCOUNT_NOT_EXIST":  50006,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{0}
}

type OperationType int32

const (
	OperationType_CREATE OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
	OperationType_AUDIT  OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "AUDIT",
	}
	OperationType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
		"AUDIT":  3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{1}
}

type CoinType int32

const (
	CoinType_CNY CoinType = 0
	CoinType_USD CoinType = 1
)

// Enum value maps for CoinType.
var (
	CoinType_name = map[int32]string{
		0: "CNY",
		1: "USD",
	}
	CoinType_value = map[string]int32{
		"CNY": 0,
		"USD": 1,
	}
)

func (x CoinType) Enum() *CoinType {
	p := new(CoinType)
	*p = x
	return p
}

func (x CoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[2].Descriptor()
}

func (CoinType) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[2]
}

func (x CoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoinType.Descriptor instead.
func (CoinType) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{2}
}

type AccountState int32

const (
	AccountState_NORMAL  AccountState = 0
	AccountState_LOCK    AccountState = 1
	AccountState_INVALID AccountState = 2
)

// Enum value maps for AccountState.
var (
	AccountState_name = map[int32]string{
		0: "NORMAL",
		1: "LOCK",
		2: "INVALID",
	}
	AccountState_value = map[string]int32{
		"NORMAL":  0,
		"LOCK":    1,
		"INVALID": 2,
	}
)

func (x AccountState) Enum() *AccountState {
	p := new(AccountState)
	*p = x
	return p
}

func (x AccountState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[3].Descriptor()
}

func (AccountState) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[3]
}

func (x AccountState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountState.Descriptor instead.
func (AccountState) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{3}
}

type AccountType int32

const (
	AccountType_PERSONAL AccountType = 0
	AccountType_COMPANY  AccountType = 1
	AccountType_SYSTEM   AccountType = 2
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "PERSONAL",
		1: "COMPANY",
		2: "SYSTEM",
	}
	AccountType_value = map[string]int32{
		"PERSONAL": 0,
		"COMPANY":  1,
		"SYSTEM":   2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[4].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes[4]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{4}
}

type CreateUserAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int64        `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Balance      string       `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"` // 余额
	CoinType     CoinType     `protobuf:"varint,3,opt,name=coin_type,json=coinType,proto3,enum=users.CoinType" json:"coin_type,omitempty"`
	CoinDesc     string       `protobuf:"bytes,4,opt,name=coin_desc,json=coinDesc,proto3" json:"coin_desc,omitempty"`
	AccountState AccountState `protobuf:"varint,5,opt,name=account_state,json=accountState,proto3,enum=users.AccountState" json:"account_state,omitempty"`
	AccountType  AccountType  `protobuf:"varint,6,opt,name=account_type,json=accountType,proto3,enum=users.AccountType" json:"account_type,omitempty"`
}

func (x *CreateUserAccountRequest) Reset() {
	*x = CreateUserAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAccountRequest) ProtoMessage() {}

func (x *CreateUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserAccountRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateUserAccountRequest) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *CreateUserAccountRequest) GetCoinType() CoinType {
	if x != nil {
		return x.CoinType
	}
	return CoinType_CNY
}

func (x *CreateUserAccountRequest) GetCoinDesc() string {
	if x != nil {
		return x.CoinDesc
	}
	return ""
}

func (x *CreateUserAccountRequest) GetAccountState() AccountState {
	if x != nil {
		return x.AccountState
	}
	return AccountState_NORMAL
}

func (x *CreateUserAccountRequest) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_PERSONAL
}

type CreateUserAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common      *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountCode string          `protobuf:"bytes,2,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"` // 用户账户code
}

func (x *CreateUserAccountResponse) Reset() {
	*x = CreateUserAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAccountResponse) ProtoMessage() {}

func (x *CreateUserAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateUserAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserAccountResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CreateUserAccountResponse) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

type GetUserInfoByPhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode string `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone       string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetUserInfoByPhoneRequest) Reset() {
	*x = GetUserInfoByPhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByPhoneRequest) ProtoMessage() {}

func (x *GetUserInfoByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoByPhoneRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetUserInfoByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetUserInfoByPhoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info   *UserInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetUserInfoByPhoneResponse) Reset() {
	*x = GetUserInfoByPhoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByPhoneResponse) ProtoMessage() {}

func (x *GetUserInfoByPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoByPhoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoByPhoneResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetUserInfoByPhoneResponse) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AccountId   string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserName    string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Sex         int32  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	CountryCode string `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone       string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email       string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	State       int32  `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	IdCardNo    string `protobuf:"bytes,9,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	Inviter     int64  `protobuf:"varint,10,opt,name=inviter,proto3" json:"inviter,omitempty"`
	InviterCode string `protobuf:"bytes,11,opt,name=inviter_code,json=inviterCode,proto3" json:"inviter_code,omitempty"`
	ContactAddr string `protobuf:"bytes,12,opt,name=contact_addr,json=contactAddr,proto3" json:"contact_addr,omitempty"`
	Age         int32  `protobuf:"varint,13,opt,name=age,proto3" json:"age,omitempty"`
	CreateTime  string `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  string `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UserInfo) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *UserInfo) GetInviter() int64 {
	if x != nil {
		return x.Inviter
	}
	return 0
}

func (x *UserInfo) GetInviterCode() string {
	if x != nil {
		return x.InviterCode
	}
	return ""
}

func (x *UserInfo) GetContactAddr() string {
	if x != nil {
		return x.ContactAddr
	}
	return ""
}

func (x *UserInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info   *UserInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetUserInfoResponse) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type MerchantsMaterialInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MaterialId   int64  `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	RegisterAddr string `protobuf:"bytes,3,opt,name=register_addr,json=registerAddr,proto3" json:"register_addr,omitempty"`
	HealthCardNo string `protobuf:"bytes,4,opt,name=health_card_no,json=healthCardNo,proto3" json:"health_card_no,omitempty"`
	Identity     int32  `protobuf:"varint,5,opt,name=identity,proto3" json:"identity,omitempty"`
	State        int32  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	TaxCardNo    string `protobuf:"bytes,7,opt,name=tax_card_no,json=taxCardNo,proto3" json:"tax_card_no,omitempty"`
	CreateTime   string `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime   string `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *MerchantsMaterialInfo) Reset() {
	*x = MerchantsMaterialInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsMaterialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsMaterialInfo) ProtoMessage() {}

func (x *MerchantsMaterialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsMaterialInfo.ProtoReflect.Descriptor instead.
func (*MerchantsMaterialInfo) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{7}
}

func (x *MerchantsMaterialInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MerchantsMaterialInfo) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *MerchantsMaterialInfo) GetRegisterAddr() string {
	if x != nil {
		return x.RegisterAddr
	}
	return ""
}

func (x *MerchantsMaterialInfo) GetHealthCardNo() string {
	if x != nil {
		return x.HealthCardNo
	}
	return ""
}

func (x *MerchantsMaterialInfo) GetIdentity() int32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

func (x *MerchantsMaterialInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *MerchantsMaterialInfo) GetTaxCardNo() string {
	if x != nil {
		return x.TaxCardNo
	}
	return ""
}

func (x *MerchantsMaterialInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MerchantsMaterialInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type MerchantsMaterialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info          *MerchantsMaterialInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	OperationType OperationType          `protobuf:"varint,2,opt,name=operation_type,json=operationType,proto3,enum=users.OperationType" json:"operation_type,omitempty"`
}

func (x *MerchantsMaterialRequest) Reset() {
	*x = MerchantsMaterialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsMaterialRequest) ProtoMessage() {}

func (x *MerchantsMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsMaterialRequest.ProtoReflect.Descriptor instead.
func (*MerchantsMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{8}
}

func (x *MerchantsMaterialRequest) GetInfo() *MerchantsMaterialInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *MerchantsMaterialRequest) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_CREATE
}

type MerchantsMaterialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common     *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	MaterialId int64           `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
}

func (x *MerchantsMaterialResponse) Reset() {
	*x = MerchantsMaterialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsMaterialResponse) ProtoMessage() {}

func (x *MerchantsMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsMaterialResponse.ProtoReflect.Descriptor instead.
func (*MerchantsMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{9}
}

func (x *MerchantsMaterialResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *MerchantsMaterialResponse) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type GetMerchantsMaterialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaterialId int64 `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
}

func (x *GetMerchantsMaterialRequest) Reset() {
	*x = GetMerchantsMaterialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchantsMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantsMaterialRequest) ProtoMessage() {}

func (x *GetMerchantsMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantsMaterialRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantsMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{10}
}

func (x *GetMerchantsMaterialRequest) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type GetMerchantsMaterialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse        `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info   *MerchantsMaterialInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetMerchantsMaterialResponse) Reset() {
	*x = GetMerchantsMaterialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMerchantsMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantsMaterialResponse) ProtoMessage() {}

func (x *GetMerchantsMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantsMaterialResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantsMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{11}
}

func (x *GetMerchantsMaterialResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetMerchantsMaterialResponse) GetInfo() *MerchantsMaterialInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type MerchantsAssociateShopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaterialId  int64 `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	ShopId      int64 `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	IsAssociate bool  `protobuf:"varint,3,opt,name=is_associate,json=isAssociate,proto3" json:"is_associate,omitempty"`
}

func (x *MerchantsAssociateShopRequest) Reset() {
	*x = MerchantsAssociateShopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsAssociateShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsAssociateShopRequest) ProtoMessage() {}

func (x *MerchantsAssociateShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsAssociateShopRequest.ProtoReflect.Descriptor instead.
func (*MerchantsAssociateShopRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{12}
}

func (x *MerchantsAssociateShopRequest) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *MerchantsAssociateShopRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *MerchantsAssociateShopRequest) GetIsAssociate() bool {
	if x != nil {
		return x.IsAssociate
	}
	return false
}

type MerchantsAssociateShopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *MerchantsAssociateShopResponse) Reset() {
	*x = MerchantsAssociateShopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsAssociateShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsAssociateShopResponse) ProtoMessage() {}

func (x *MerchantsAssociateShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsAssociateShopResponse.ProtoReflect.Descriptor instead.
func (*MerchantsAssociateShopResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{13}
}

func (x *MerchantsAssociateShopResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

type MerchantsMaterialAuditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaterialId int64  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	AuditUid   int64  `protobuf:"varint,2,opt,name=audit_uid,json=auditUid,proto3" json:"audit_uid,omitempty"`
	Comment    string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *MerchantsMaterialAuditRequest) Reset() {
	*x = MerchantsMaterialAuditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsMaterialAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsMaterialAuditRequest) ProtoMessage() {}

func (x *MerchantsMaterialAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsMaterialAuditRequest.ProtoReflect.Descriptor instead.
func (*MerchantsMaterialAuditRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{14}
}

func (x *MerchantsMaterialAuditRequest) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *MerchantsMaterialAuditRequest) GetAuditUid() int64 {
	if x != nil {
		return x.AuditUid
	}
	return 0
}

func (x *MerchantsMaterialAuditRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type MerchantsMaterialAuditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common       *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	State        int32           `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Comment      string          `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	NextAuditUid int64           `protobuf:"varint,4,opt,name=next_audit_uid,json=nextAuditUid,proto3" json:"next_audit_uid,omitempty"`
	IsOver       bool            `protobuf:"varint,5,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
}

func (x *MerchantsMaterialAuditResponse) Reset() {
	*x = MerchantsMaterialAuditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantsMaterialAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantsMaterialAuditResponse) ProtoMessage() {}

func (x *MerchantsMaterialAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantsMaterialAuditResponse.ProtoReflect.Descriptor instead.
func (*MerchantsMaterialAuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{15}
}

func (x *MerchantsMaterialAuditResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *MerchantsMaterialAuditResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *MerchantsMaterialAuditResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MerchantsMaterialAuditResponse) GetNextAuditUid() int64 {
	if x != nil {
		return x.NextAuditUid
	}
	return 0
}

func (x *MerchantsMaterialAuditResponse) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code RetCode `protobuf:"varint,1,opt,name=code,proto3,enum=users.RetCode" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP(), []int{16}
}

func (x *CommonResponse) GetCode() RetCode {
	if x != nil {
		return x.Code
	}
	return RetCode_SUCCESS
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto protoreflect.FileDescriptor

var file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDesc = []byte{
	0x0a, 0x45, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x5f, 0x6d, 0x61,
	0x6c, 0x6c, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x5f, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x3e,
	0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x6c, 0x76, 0x69, 0x6e,
	0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82,
	0x02, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x38, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x6d, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x54, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x70, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x26, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0xa1, 0x03, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x6e, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64,
	0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x69, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0xa9, 0x02, 0x0a, 0x15, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x74,
	0x61, 0x78, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x61, 0x78, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x89, 0x01,
	0x0a, 0x18, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x3b, 0x0a, 0x0e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6b, 0x0a, 0x19, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x7c, 0x0a, 0x1d, 0x4d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x73, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x73, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x1e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x73, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x77, 0x0a, 0x1d, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x75, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69,
	0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x75, 0x64,
	0x69, 0x74, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0xbe, 0x01, 0x0a, 0x1e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x75, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f,
	0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x55, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6f, 0x76,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x76, 0x65, 0x72,
	0x22, 0x46, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0xa8, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xf4, 0x03, 0x12, 0x14, 0x0a,
	0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10,
	0xd1, 0x86, 0x03, 0x12, 0x10, 0x0a, 0x0a, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x45, 0x58, 0x49, 0x53,
	0x54, 0x10, 0xd2, 0x86, 0x03, 0x12, 0x18, 0x0a, 0x12, 0x4d, 0x45, 0x52, 0x43, 0x48, 0x41, 0x4e,
	0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd3, 0x86, 0x03, 0x12,
	0x14, 0x0a, 0x0e, 0x4d, 0x45, 0x52, 0x43, 0x48, 0x41, 0x4e, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53,
	0x54, 0x10, 0xd4, 0x86, 0x03, 0x12, 0x13, 0x0a, 0x0d, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd5, 0x86, 0x03, 0x12, 0x17, 0x0a, 0x11, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10,
	0xd6, 0x86, 0x03, 0x2a, 0x3e, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44, 0x49,
	0x54, 0x10, 0x03, 0x2a, 0x1c, 0x0a, 0x08, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x07, 0x0a, 0x03, 0x43, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53, 0x44, 0x10,
	0x01, 0x2a, 0x31, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x02, 0x2a, 0x34, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x41, 0x4c, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x02, 0x32, 0xe2, 0x02, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x79, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x20,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x62, 0x79, 0x5f, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x7a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1c, 0x22, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x32,
	0xc5, 0x04, 0x0a, 0x10, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x11, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x20, 0x22, 0x1b, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x3a, 0x01, 0x2a, 0x12, 0x8a, 0x01, 0x0a, 0x16, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x75, 0x64, 0x69, 0x74, 0x12,
	0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x75, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1d, 0x1a, 0x18, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x3a, 0x01,
	0x2a, 0x12, 0x84, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x2f,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x9c, 0x01, 0x0a, 0x16, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x70, 0x12, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x73, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x41, 0x73, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x35, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2f, 0x1a, 0x2a, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x61, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x3a, 0x01, 0x2a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescOnce sync.Once
	file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescData = file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDesc
)

func file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescGZIP() []byte {
	file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescOnce.Do(func() {
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescData)
	})
	return file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDescData
}

var file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_goTypes = []interface{}{
	(RetCode)(0),                           // 0: users.RetCode
	(OperationType)(0),                     // 1: users.OperationType
	(CoinType)(0),                          // 2: users.CoinType
	(AccountState)(0),                      // 3: users.AccountState
	(AccountType)(0),                       // 4: users.AccountType
	(*CreateUserAccountRequest)(nil),       // 5: users.CreateUserAccountRequest
	(*CreateUserAccountResponse)(nil),      // 6: users.CreateUserAccountResponse
	(*GetUserInfoByPhoneRequest)(nil),      // 7: users.GetUserInfoByPhoneRequest
	(*GetUserInfoByPhoneResponse)(nil),     // 8: users.GetUserInfoByPhoneResponse
	(*GetUserInfoRequest)(nil),             // 9: users.GetUserInfoRequest
	(*UserInfo)(nil),                       // 10: users.UserInfo
	(*GetUserInfoResponse)(nil),            // 11: users.GetUserInfoResponse
	(*MerchantsMaterialInfo)(nil),          // 12: users.MerchantsMaterialInfo
	(*MerchantsMaterialRequest)(nil),       // 13: users.MerchantsMaterialRequest
	(*MerchantsMaterialResponse)(nil),      // 14: users.MerchantsMaterialResponse
	(*GetMerchantsMaterialRequest)(nil),    // 15: users.GetMerchantsMaterialRequest
	(*GetMerchantsMaterialResponse)(nil),   // 16: users.GetMerchantsMaterialResponse
	(*MerchantsAssociateShopRequest)(nil),  // 17: users.MerchantsAssociateShopRequest
	(*MerchantsAssociateShopResponse)(nil), // 18: users.MerchantsAssociateShopResponse
	(*MerchantsMaterialAuditRequest)(nil),  // 19: users.MerchantsMaterialAuditRequest
	(*MerchantsMaterialAuditResponse)(nil), // 20: users.MerchantsMaterialAuditResponse
	(*CommonResponse)(nil),                 // 21: users.CommonResponse
}
var file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_depIdxs = []int32{
	2,  // 0: users.CreateUserAccountRequest.coin_type:type_name -> users.CoinType
	3,  // 1: users.CreateUserAccountRequest.account_state:type_name -> users.AccountState
	4,  // 2: users.CreateUserAccountRequest.account_type:type_name -> users.AccountType
	21, // 3: users.CreateUserAccountResponse.common:type_name -> users.CommonResponse
	21, // 4: users.GetUserInfoByPhoneResponse.common:type_name -> users.CommonResponse
	10, // 5: users.GetUserInfoByPhoneResponse.info:type_name -> users.UserInfo
	21, // 6: users.GetUserInfoResponse.common:type_name -> users.CommonResponse
	10, // 7: users.GetUserInfoResponse.info:type_name -> users.UserInfo
	12, // 8: users.MerchantsMaterialRequest.info:type_name -> users.MerchantsMaterialInfo
	1,  // 9: users.MerchantsMaterialRequest.operation_type:type_name -> users.OperationType
	21, // 10: users.MerchantsMaterialResponse.common:type_name -> users.CommonResponse
	21, // 11: users.GetMerchantsMaterialResponse.common:type_name -> users.CommonResponse
	12, // 12: users.GetMerchantsMaterialResponse.info:type_name -> users.MerchantsMaterialInfo
	21, // 13: users.MerchantsAssociateShopResponse.common:type_name -> users.CommonResponse
	21, // 14: users.MerchantsMaterialAuditResponse.common:type_name -> users.CommonResponse
	0,  // 15: users.CommonResponse.code:type_name -> users.RetCode
	9,  // 16: users.UsersService.GetUserInfo:input_type -> users.GetUserInfoRequest
	7,  // 17: users.UsersService.GetUserInfoByPhone:input_type -> users.GetUserInfoByPhoneRequest
	5,  // 18: users.UsersService.CreateUserAccount:input_type -> users.CreateUserAccountRequest
	13, // 19: users.MerchantsService.MerchantsMaterial:input_type -> users.MerchantsMaterialRequest
	19, // 20: users.MerchantsService.MerchantsMaterialAudit:input_type -> users.MerchantsMaterialAuditRequest
	15, // 21: users.MerchantsService.GetMerchantsMaterial:input_type -> users.GetMerchantsMaterialRequest
	17, // 22: users.MerchantsService.MerchantsAssociateShop:input_type -> users.MerchantsAssociateShopRequest
	11, // 23: users.UsersService.GetUserInfo:output_type -> users.GetUserInfoResponse
	8,  // 24: users.UsersService.GetUserInfoByPhone:output_type -> users.GetUserInfoByPhoneResponse
	6,  // 25: users.UsersService.CreateUserAccount:output_type -> users.CreateUserAccountResponse
	14, // 26: users.MerchantsService.MerchantsMaterial:output_type -> users.MerchantsMaterialResponse
	20, // 27: users.MerchantsService.MerchantsMaterialAudit:output_type -> users.MerchantsMaterialAuditResponse
	16, // 28: users.MerchantsService.GetMerchantsMaterial:output_type -> users.GetMerchantsMaterialResponse
	18, // 29: users.MerchantsService.MerchantsAssociateShop:output_type -> users.MerchantsAssociateShopResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_init() }
func file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_init() {
	if File_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByPhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByPhoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsMaterialInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsMaterialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsMaterialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMerchantsMaterialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMerchantsMaterialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsAssociateShopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsAssociateShopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsMaterialAuditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantsMaterialAuditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_goTypes,
		DependencyIndexes: file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_depIdxs,
		EnumInfos:         file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_enumTypes,
		MessageInfos:      file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_msgTypes,
	}.Build()
	File_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto = out.File
	file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_rawDesc = nil
	file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_goTypes = nil
	file_proto_micro_mall_order_proto_micro_mall_users_proto_users_users_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// 获取用户信息-手机号
	GetUserInfoByPhone(ctx context.Context, in *GetUserInfoByPhoneRequest, opts ...grpc.CallOption) (*GetUserInfoByPhoneResponse, error)
	// 创建用户账户
	CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountResponse, error)
}

type usersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceClient(cc grpc.ClientConnInterface) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserInfoByPhone(ctx context.Context, in *GetUserInfoByPhoneRequest, opts ...grpc.CallOption) (*GetUserInfoByPhoneResponse, error) {
	out := new(GetUserInfoByPhoneResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/GetUserInfoByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountResponse, error) {
	out := new(CreateUserAccountResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/CreateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// 获取用户信息-手机号
	GetUserInfoByPhone(context.Context, *GetUserInfoByPhoneRequest) (*GetUserInfoByPhoneResponse, error)
	// 创建用户账户
	CreateUserAccount(context.Context, *CreateUserAccountRequest) (*CreateUserAccountResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedUsersServiceServer) GetUserInfoByPhone(context.Context, *GetUserInfoByPhoneRequest) (*GetUserInfoByPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoByPhone not implemented")
}
func (*UnimplementedUsersServiceServer) CreateUserAccount(context.Context, *CreateUserAccountRequest) (*CreateUserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAccount not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserInfoByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserInfoByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/GetUserInfoByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserInfoByPhone(ctx, req.(*GetUserInfoByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/CreateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUserAccount(ctx, req.(*CreateUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UsersService_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserInfoByPhone",
			Handler:    _UsersService_GetUserInfoByPhone_Handler,
		},
		{
			MethodName: "CreateUserAccount",
			Handler:    _UsersService_CreateUserAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_order/proto/micro_mall_users_proto/users/users.proto",
}

// MerchantsServiceClient is the client API for MerchantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantsServiceClient interface {
	// 商户提交资料
	MerchantsMaterial(ctx context.Context, in *MerchantsMaterialRequest, opts ...grpc.CallOption) (*MerchantsMaterialResponse, error)
	// 审核商户,返回审核结果
	MerchantsMaterialAudit(ctx context.Context, in *MerchantsMaterialAuditRequest, opts ...grpc.CallOption) (*MerchantsMaterialAuditResponse, error)
	// 获取商户资料
	GetMerchantsMaterial(ctx context.Context, in *GetMerchantsMaterialRequest, opts ...grpc.CallOption) (*GetMerchantsMaterialResponse, error)
	// 商户关联店铺
	MerchantsAssociateShop(ctx context.Context, in *MerchantsAssociateShopRequest, opts ...grpc.CallOption) (*MerchantsAssociateShopResponse, error)
}

type merchantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantsServiceClient(cc grpc.ClientConnInterface) MerchantsServiceClient {
	return &merchantsServiceClient{cc}
}

func (c *merchantsServiceClient) MerchantsMaterial(ctx context.Context, in *MerchantsMaterialRequest, opts ...grpc.CallOption) (*MerchantsMaterialResponse, error) {
	out := new(MerchantsMaterialResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) MerchantsMaterialAudit(ctx context.Context, in *MerchantsMaterialAuditRequest, opts ...grpc.CallOption) (*MerchantsMaterialAuditResponse, error) {
	out := new(MerchantsMaterialAuditResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsMaterialAudit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) GetMerchantsMaterial(ctx context.Context, in *GetMerchantsMaterialRequest, opts ...grpc.CallOption) (*GetMerchantsMaterialResponse, error) {
	out := new(GetMerchantsMaterialResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/GetMerchantsMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) MerchantsAssociateShop(ctx context.Context, in *MerchantsAssociateShopRequest, opts ...grpc.CallOption) (*MerchantsAssociateShopResponse, error) {
	out := new(MerchantsAssociateShopResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsAssociateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantsServiceServer is the server API for MerchantsService service.
type MerchantsServiceServer interface {
	// 商户提交资料
	MerchantsMaterial(context.Context, *MerchantsMaterialRequest) (*MerchantsMaterialResponse, error)
	// 审核商户,返回审核结果
	MerchantsMaterialAudit(context.Context, *MerchantsMaterialAuditRequest) (*MerchantsMaterialAuditResponse, error)
	// 获取商户资料
	GetMerchantsMaterial(context.Context, *GetMerchantsMaterialRequest) (*GetMerchantsMaterialResponse, error)
	// 商户关联店铺
	MerchantsAssociateShop(context.Context, *MerchantsAssociateShopRequest) (*MerchantsAssociateShopResponse, error)
}

// UnimplementedMerchantsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantsServiceServer struct {
}

func (*UnimplementedMerchantsServiceServer) MerchantsMaterial(context.Context, *MerchantsMaterialRequest) (*MerchantsMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsMaterial not implemented")
}
func (*UnimplementedMerchantsServiceServer) MerchantsMaterialAudit(context.Context, *MerchantsMaterialAuditRequest) (*MerchantsMaterialAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsMaterialAudit not implemented")
}
func (*UnimplementedMerchantsServiceServer) GetMerchantsMaterial(context.Context, *GetMerchantsMaterialRequest) (*GetMerchantsMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantsMaterial not implemented")
}
func (*UnimplementedMerchantsServiceServer) MerchantsAssociateShop(context.Context, *MerchantsAssociateShopRequest) (*MerchantsAssociateShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsAssociateShop not implemented")
}

func RegisterMerchantsServiceServer(s *grpc.Server, srv MerchantsServiceServer) {
	s.RegisterService(&_MerchantsService_serviceDesc, srv)
}

func _MerchantsService_MerchantsMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsMaterial(ctx, req.(*MerchantsMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_MerchantsMaterialAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsMaterialAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsMaterialAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsMaterialAudit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsMaterialAudit(ctx, req.(*MerchantsMaterialAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_GetMerchantsMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantsMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).GetMerchantsMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/GetMerchantsMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).GetMerchantsMaterial(ctx, req.(*GetMerchantsMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_MerchantsAssociateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsAssociateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsAssociateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsAssociateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsAssociateShop(ctx, req.(*MerchantsAssociateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.MerchantsService",
	HandlerType: (*MerchantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MerchantsMaterial",
			Handler:    _MerchantsService_MerchantsMaterial_Handler,
		},
		{
			MethodName: "MerchantsMaterialAudit",
			Handler:    _MerchantsService_MerchantsMaterialAudit_Handler,
		},
		{
			MethodName: "GetMerchantsMaterial",
			Handler:    _MerchantsService_GetMerchantsMaterial_Handler,
		},
		{
			MethodName: "MerchantsAssociateShop",
			Handler:    _MerchantsService_MerchantsAssociateShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_order/proto/micro_mall_users_proto/users/users.proto",
}
