version: '3.1'
networks:
  default:
    external:
      name: etcd-cluster
services:
  etcd_cluster_node1:
    image:  quay.io/coreos/etcd:v3.2.32
    container_name: etcd_cluster_node1
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd_cluster_node1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd_cluster_node1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_cluster_node1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd_cluster_node1=http://etcd_cluster_node1:2380,etcd_cluster_node2=http://etcd_cluster_node2:2380,etcd_cluster_node3=http://etcd_cluster_node3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCDCTL_API=3
    ports:
      - 12379:2379
      - 12380:2380
  etcd_cluster_node2:
    image:  quay.io/coreos/etcd:v3.2.32
    container_name: etcd_cluster_node2
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd_cluster_node2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd_cluster_node2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_cluster_node2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd_cluster_node1=http://etcd_cluster_node1:2380,etcd_cluster_node2=http://etcd_cluster_node2:2380,etcd_cluster_node3=http://etcd_cluster_node3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCDCTL_API=3
    ports:
      - 22379:2379
      - 22380:2380
  etcd_cluster_node3:
    image:  quay.io/coreos/etcd:v3.2.32
    container_name: etcd_cluster_node3
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd_cluster_node3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd_cluster_node3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_cluster_node3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd_cluster_node1=http://etcd_cluster_node1:2380,etcd_cluster_node2=http://etcd_cluster_node2:2380,etcd_cluster_node3=http://etcd_cluster_node3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCDCTL_API=3
    ports:
      - 32379:2379
      - 32380:2380